%YAML 1.2
---
- name: Cenozoic
  color: F2F91D
  sub:
    - name: Quaternary
      color: F9F97F
      sub:
        - name: Holocene
          color: FEF2E0
        - name: Pleistocene
          color: FEF2E0
    - name: Neogene
      color: FFE619
      sub:
        - name: Pliocene
          color: FFFF99
        - name: Miocene
          color: FFFF00
    - name: Paleogene
      color: FD9A52
- name: Mesozoic
  color: 67C5CA
  sub:
    - name: Cretaceous
      color: 7FC64E
    - name: Jurassic
      color: 34B2C9
    - name: Triassic
      color: 812B92
      white: True
- name: Paleozoic
  color: 99C08D
  sub:
    - name: Permian
      color: F04028
    - name: Carboniferous
      color: 67A599
    - name: Devonian
      color: CB8C37
    - name: Silurian
      color: B3E1B6
    - name: Ordovician
      color: 009270
      white: True
    - name: Cambrian
      color: 7FA056
- name: Precambrian
  color: F74370
